spring:
  application:
    name: autofolio-api
  
  # Java 21 Virtual Threads Activation (Global)
  threads:
    virtual:
      enabled: true

  # Common JSON Formatting
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      write-dates-as-timestamps: false

# Monitoring & Health
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# API Documentation Base
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
